import type { Metadata } from "next";
import { Gothic_A1 } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import SessionProviders from "@/providers/session";

const inter = Gothic_A1({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProviders>
        <body className={inter.className}>{children}</body>
      </SessionProviders>
    </html>
  );
}
